### ISSUE TITLE
semantic release versioning please

### ISSUE THREAD

**Issue by onlyjob** [mattn/go-runewidth#10]
See 

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions)

Thanks.

**Comment by mattn** [comment]
done https://github.com/mattn/go-runewidth/tree/v0.0.1

**Comment by onlyjob** [comment]
Awesome! Thank you. :)
