### ISSUE TITLE
hello,I have a problem.

### ISSUE THREAD

**Issue by duanjunxiao** [mattn/go-runewidth#12]
```
bash-3.2$ go get -u -d github.com/coreos/etcd/...
# cd .; git clone https://github.com/mattn/go-runewidth /Users/admin/go/src/github.com/mattn/go-runewidth
fatal: could not create work tree dir '/Users/admin/go/src/github.com/mattn/go-runewidth': Permission denied
package github.com/mattn/go-runewidth: exit status 128
```

**Comment by shurcooL** [comment]
That looks like an issue local to your setup, not an issue wit this package.

It seems you don't have write permissions in `/Users/admin/go/src/github.com/mattn/go-runewidth` directory, or whichever parent exists. It's unable to create a directory in order to clone the repository.
