### ISSUE TITLE
The width of Box-drawing characters

### ISSUE THREAD

**Issue by NonerKao** [mattn/go-runewidth#14]
Check [this](https://en.wikipedia.org/wiki/Box-drawing_character) for the definition of box-drawing (BD below) characters.

I found that these characters are defined to be of **ambiguous** width, so passing these  to `RuneWidth` returns 2 in my environment.  This is somehow inconvenient since AFAIK, terminal fonts tend to interpret BD characters in half-width.  

Is it possible to remove these characters from the ambiguous table?  I can make the PR if you think this sounds sane.

Thanks.

**Comment by mattn** [comment]
It is depend on $LANG. And you can modify it to set EastAsianWidth.

**Comment by mattn** [comment]
Now I added environment variable `github.com/mattn/go-runewidth#IsEastAsian`. You can modify it if you want to change behaivor.

**Comment by NonerKao** [comment]
Thanks for the quick reply.

Just a feedback for this patch: for some shell, such as `sh` or `bash`, `github.com/mattn/go-runewidth#IsEastAsian` is not a valid name for environment variable.

**Comment by mattn** [comment]
renamed to RUNEWIDTH_EASTASIAN.

**Comment by nzlov** [comment]
Hi @mattn, When `LC_CTYPE=zh_CN.UTF-8`, `RUNEWIDTH_EASTASIAN` is invalid. Box-drawing (BD below) characters, `RuneWidth` returns `2`

**Comment by mattn** [comment]
What character do you mean?

```
=│=
=AA=
```
Please try to paste above text on your terminal. This is my environment. UNIX.

![38ea1497442d9a19](https://user-images.githubusercontent.com/10111/38356081-b4572a08-38f9-11e8-81f3-1ebb99ac125f.png)

And Windows cmd.exe

![d6860f291190eed6](https://user-images.githubusercontent.com/10111/38356115-d20023de-38f9-11e8-8d6c-8efdb901ab96.png)

**Comment by nzlov** [comment]
`LC_CTYPE=zh_CN.UTF-8 RUNEWIDTH_EASTASIAN=0`:
![511aac51-1158-4e34-85e7-7e74a15b527d](https://user-images.githubusercontent.com/2859981/38374176-99a36ba0-3925-11e8-981b-a0d5277d693a.png)
`LC_CTYPE=en_US.UTF-8`:
![10897581-0eeb-475c-ab7c-d42e11ce4c55](https://user-images.githubusercontent.com/2859981/38374179-9a323984-3925-11e8-9de3-0e7fe8ebf421.png)


Macos 10.12.6 zh_CN iterm2 zsh
```
=│=
=AA=
```
![image](https://user-images.githubusercontent.com/2859981/38374359-017aeaaa-3926-11e8-883e-016018dc8423.png)

**Comment by mattn** [comment]
Do you want to forcibly disable RUNEWIDTH_EASTASIAN ?

**Comment by mattn** [comment]
How about this patch ?
```diff
diff --git a/runewidth.go b/runewidth.go
index 70de0dc..82568a1 100644
--- a/runewidth.go
+++ b/runewidth.go
@@ -4,12 +4,21 @@ import "os"
 
 var (
 	// EastAsianWidth will be set true if the current locale is CJK
-	EastAsianWidth = os.Getenv("RUNEWIDTH_EASTASIAN") == "1" || IsEastAsian()
+	EastAsianWidth bool
 
 	// DefaultCondition is a condition in current locale
 	DefaultCondition = &Condition{EastAsianWidth}
 )
 
+func init() {
+	env := os.Getenv("RUNEWIDTH_EASTASIAN")
+	if env == "" {
+		EastAsianWidth = IsEastAsian()
+	} else {
+		EastAsianWidth = env == "1"
+	}
+}
+
 type interval struct {
 	first rune
 	last  rune
```

**Comment by nzlov** [comment]
Good idea, but why not force return 1?

**Comment by mattn** [comment]
What do you mean "return"?

**Comment by nzlov** [comment]
I want to remove these characters `box-drawing` from the ambiguous table

**Comment by mattn** [comment]
Unfortunately, box-drawing characters are listed in ambiguous width characters.

http://www.unicode.org/reports/tr11-2/

**Comment by nzlov** [comment]
@mattn Ok,thanks.
