### ISSUE TITLE
Regional Indicators (Flags) and Grapheme Clusters

### ISSUE THREAD

**Issue by rivo** [mattn/go-runewidth#28]
Here's a short example that illustrates an issue with flags (or "regional indicators"):

```go
fmt.Println(runewidth.StringWidth("🇩🇪")) // Should be "2", outputs "4".
```

The flag consists of two code points which are processed separately by `runewidth`. But most modern systems will combine them into one flag emoji.

This is part of a larger topic which I describe in more detail here: gdamore/tcell#264. It doesn't just affect flags but also characters in e.g. Arabic and Korean where there are more sophisticated rules than "combining characters" and zero-width joiners (which you added with #20).

I don't know exactly how you calculate the widths of characters. I'm also not sure how you would solve flags as well as some of the other rules described in the [Unicode specification](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules) but it would sure be nice as printing these flags currently gives me trouble in [`tview`](https://github.com/rivo/tview). There have been multiple issues asking for better support for different languages and emojis so it seems that there are quite a few people who use the terminal with these characters.

(Maybe my new package [`uniseg`](https://github.com/rivo/uniseg) can help you here.)

**Comment by rivo** [comment]
Here's my own implementation of the "string width" function which takes grapheme clusters into account:

https://github.com/rivo/tview/blob/8d5eba0c2f51d8ae971c5a470e354bbc2aae6777/util.go#L419

It's based on the assumption that the width of a grapheme cluster is the width of the first non-zero-width rune. That's just my guess but it works fine for a bunch of examples I tried manually.

Maybe you want to use this implementation in your package. I think it would definitively improve the calculation of a string width. You could then also get rid of the special zero-width-joiner handling as it's all implicit in the `uniseg` package.

**Comment by mattn** [comment]
Could you please send me PR?

**Comment by alecrabbit** [comment]
Hi! I'm not sure if this issues related but assume they are.
characters `{"←", "↖", "↑", "↗", "→", "↘", "↓", "↙"}` accepted by my terminal as of width 1 and all is working as it should, however `runewidth.StringWidth(char)` is giving `[1 2 1 2 1 2 1 2]` correspondingly and that breaks output

```text
// Character StringWidth uniseg.Graphemes
    ←         1           [2190]
    ↖         2           [2196]
    ↑         1           [2191]
    ↗         2           [2197]
    →         1           [2192]
    ↘         2           [2198]
    ↓         1           [2193]
    ↙         2           [2199]
```
same for 
```text
// Character StringWidth uniseg.Graphemes
    ■         1           [25a0]
    □         1           [25a1]
    ▪         2           [25aa]
    ▫         2           [25ab]
```
I hope this additional info will help.

> My php package [`php-wcwidth`](https://github.com/alecrabbit/php-wcwidth) (which is practically a dumb clone of python's [`jquast/wcwidth`](https://github.com/jquast/wcwidth)) gets widths of these chars correctly

**Comment by mattn** [comment]
Thank you. Could you please show me screenshot?

This is an screenshot taken on my environment.

![image](https://user-images.githubusercontent.com/10111/65335578-a2717a00-dbff-11e9-84bb-506b9a7c1e07.png)

**Comment by alecrabbit** [comment]
this one?
![image](https://user-images.githubusercontent.com/11045453/65335734-a4bae080-dbcd-11e9-8190-d767992dac85.png)

**Comment by alecrabbit** [comment]
same but larger
![image](https://user-images.githubusercontent.com/11045453/65335832-d7fd6f80-dbcd-11e9-97ed-81d6c524c41f.png)

**Comment by alecrabbit** [comment]
and from terminal
![image](https://user-images.githubusercontent.com/11045453/65336083-59ed9880-dbce-11e9-8449-23f95e976f3b.png)

**Comment by mattn** [comment]
What is your $LANG?

**Comment by alecrabbit** [comment]
LANG=en_US.UTF-8

**Comment by mattn** [comment]
@joshuarubin 0x2194 in emoji is correctly?

**Comment by alecrabbit** [comment]
@mattn here's what I found out:
these do not have an emojis
![image](https://user-images.githubusercontent.com/11045453/65339388-b8b61080-dbd4-11e9-9788-cd33c842b2de.png)

but these do:
![image](https://user-images.githubusercontent.com/11045453/65339463-de431a00-dbd4-11e9-9b76-56daf9301e72.png)

**Comment by alecrabbit** [comment]
and my terminal can print them both
![image](https://user-images.githubusercontent.com/11045453/65339843-94a6ff00-dbd5-11e9-8d5a-51d69cd5c529.png)
however, I'm unable to figure out how to print it from my code
printing by code gives `↔` copy-pasting also gives `↔`

**Comment by alecrabbit** [comment]
it seems like `2194` is followed by `fe0f` to print emoji
so `2194 fe0f`
