### ISSUE TITLE
Rune width of certain CP437 chars like ♦ is 2 instead of 1

### ISSUE THREAD

**Issue by benhoyt** [mattn/go-runewidth#34]
I'm trying to port an old DOS program using tcell (which uses RuneWidth). My program has a table mapping CP437 char code to rune, and then I print that rune to the screen. I'm in the terminal with fixed width fonts, so I expect all chars to be the same width.

The issue is `RuneWidth('\u2666')` and some other characters is returning width 2 instead of 1, which makes tcell allocate 2 chars for it and causes "gaps" in the rendering. Here's playground code showing which chars do this: https://play.golang.org/p/Hjq3GOC0Pcd -- output is:

```
RuneWidth('☺') = 2
RuneWidth('☻') = 2
RuneWidth('♥') = 2
RuneWidth('♦') = 2
RuneWidth('♣') = 2
RuneWidth('♠') = 2
RuneWidth('♂') = 2
RuneWidth('♀') = 2
RuneWidth('♪') = 2
RuneWidth('♫') = 2
RuneWidth('☼') = 2
RuneWidth('↕') = 2
RuneWidth('‼') = 2
RuneWidth('↔') = 2
```

I believe it's happening because these are treated as Emoji characters. Is this behavior expected? If so, how do I work around this in tcell?

**Comment by mattn** [comment]
Could you please try https://github.com/mattn/go-runewidth/pull/35 ?

**Comment by benhoyt** [comment]
Thanks for the quick response -- I've tested in my codebase and this works for me! I'm somewhat ignorant about all this and would love to learn more: can you please explain what's going on here in a bit more detail, i.e., why `emoji` was checked in the first place, and why it's not needed anymore?

**Comment by mattn** [comment]
It was checked for that east asian. On east asian, anbiguous width characters and emojis both are double width always. But Unicode 12 have correct width. So it is not needed at least.

**Comment by mattn** [comment]
Thank you.

**Comment by benhoyt** [comment]
Great, thanks!
