### ISSUE TITLE
`─` not expect

### ISSUE THREAD

**Issue by lysShub** [mattn/go-runewidth#69]
```go
func main() {
	b := `─` // unicode 0x2500
	fmt.Println(runewidth.StringWidth(b))
}
```

on windows/mac get: 2
on linux get: 1

**Comment by lysShub** [comment]
Windows
```
```

**Comment by mattn** [comment]
Yes, go-runewidth return 2 for `─` on CJK locales.

**Comment by mattn** [comment]
If you don't want that go-runewidth detect locales, set RUNEWIDTH_EASTASIAN=0
